/* 
 * APIKeyAPI v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DefaultApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DefaultApiTests
    {
        private DefaultApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DefaultApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DefaultApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DefaultApi
            //Assert.IsInstanceOfType(typeof(DefaultApi), instance, "instance is a DefaultApi");
        }

        /// <summary>
        /// Test DeleteKeyId
        /// </summary>
        [Test]
        public void DeleteKeyIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //instance.DeleteKeyId(id);
            
        }
        /// <summary>
        /// Test Get
        /// </summary>
        [Test]
        public void GetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.Get();
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        /// <summary>
        /// Test GetKeyId
        /// </summary>
        [Test]
        public void GetKeyIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //instance.GetKeyId(id);
            
        }
        /// <summary>
        /// Test GetKeyName
        /// </summary>
        [Test]
        public void GetKeyNameTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string keyName = null;
            //instance.GetKeyName(keyName);
            
        }
        /// <summary>
        /// Test PostKey
        /// </summary>
        [Test]
        public void PostKeyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SecretKey body = null;
            //instance.PostKey(body);
            
        }
        /// <summary>
        /// Test PutKeyId
        /// </summary>
        [Test]
        public void PutKeyIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SecretKey body = null;
            //int? id = null;
            //instance.PutKeyId(body, id);
            
        }
        /// <summary>
        /// Test PutKeyName
        /// </summary>
        [Test]
        public void PutKeyNameTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SecretKey body = null;
            //string keyName = null;
            //instance.PutKeyName(body, keyName);
            
        }
    }

}
