/* 
 * APIKeyAPI v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SecretKey
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SecretKeyTests
    {
        // TODO uncomment below to declare an instance variable for SecretKey
        //private SecretKey instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SecretKey
            //instance = new SecretKey();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SecretKey
        /// </summary>
        [Test]
        public void SecretKeyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SecretKey
            //Assert.IsInstanceOfType<SecretKey> (instance, "variable 'instance' is a SecretKey");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'KeyName'
        /// </summary>
        [Test]
        public void KeyNameTest()
        {
            // TODO unit test for the property 'KeyName'
        }
        /// <summary>
        /// Test the property 'SecretValue'
        /// </summary>
        [Test]
        public void SecretValueTest()
        {
            // TODO unit test for the property 'SecretValue'
        }

    }

}
